
services: 
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment: 
      POSTGERES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: basesita
    ports: 
      - 5432:5432
    volumes: 
      - ./data:/var/lib/postgresql/data
    
